#!/usr/bin/env bash
# Contract checks for the two-pane-workflow skill. Run: tests/test-skill.sh
#
# The frontmatter is the interface both harnesses parse; the checks pin the
# name, trigger, role contract, and delegation to the deterministic helper.
set -u
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cp "$REPO_ROOT/2pane" "$TMP/2pane"
chmod +x "$TMP/2pane"
"$TMP/2pane" init >/dev/null
SKILL="$TMP/.agents/skills/two-pane-workflow/SKILL.md"

pass=0
fail=0
check() { # label exit-code
  if [ "$2" -eq 0 ]; then
    pass=$((pass + 1)); echo "ok - $1"
  else
    fail=$((fail + 1)); echo "not ok - $1"
  fi
}

if [ -f "$SKILL" ]; then
  check "skill exists at the spec path .agents/skills/two-pane-workflow" 0
else
  check "skill exists at the spec path .agents/skills/two-pane-workflow" 1
fi
head -1 "$SKILL" | grep -q '^---$'; check "frontmatter opens with a YAML delimiter" $?
awk '/^---$/{c++} c==1' "$SKILL" | grep -q '^name: two-pane-workflow$'; check "frontmatter declares the skill name" $?
awk '/^---$/{c++} c==1' "$SKILL" | grep -q '^description: .*\binbox\b'; check "description carries the inbox trigger branch" $?
awk '/^---$/{c++} c==1' "$SKILL" | grep -q '^description: 2pane '; check "description leads with the command trigger" $?
grep -q 'AGENT_ROLE' "$SKILL"; check "body detects the role via AGENT_ROLE" $?
grep -Fqx '<!-- Managed by ./2pane init. -->' "$SKILL"; check "skill is marked as generated by init" $?
grep -q 'human.*serializes.*inbox action' "$SKILL"; check "human serializes inbox actions" $?
grep -q '\./2pane take' "$SKILL"; check "consume delegates to 2pane take" $?
grep -q '\./2pane send' "$SKILL"; check "writes delegate to 2pane send" $?
grep -q 'directly.*\./2pane send' "$SKILL"; check "reply sends directly without another read" $?
grep -q 'send.*performs the slot check' "$SKILL"; check "send owns the slot check" $?
grep -q 'yield until the human requests the next inbox action' "$SKILL"; check "send yields to the human router" $?
grep -q 'Never inspect.*\.2pane/' "$SKILL"; check "skill forbids direct .2pane inspection" $?
grep -q 'only its requested result fields' "$SKILL"; check "reply stays scoped to requested fields" $?
word_count="$(wc -w < "$SKILL")"
[ "$word_count" -le 120 ]; check "skill stays within its 120-word context budget" $?

echo "---"
echo "pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
